version: "3.9"
services:

  server:
    build: .
    ports:
      - 3001:3000
      - 5000:5000
    volumes:
      - '.:/app'
      - '/app/node_modules'
    environment:
      - CHOKIDAR_USEPOLLING=true